version: 2
jobs:
  tests:
    description: "Run tests"
    working_directory: ~/users
    docker:

      - image: circleci/python:3.7.2
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: echo "Run tests"
      - run: pip install --user --upgrade pip
      - run: pip install --user -r requirements.txt
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
      - run:
          name: run tests
          command: |
            set -e
            . venv/bin/activate
            mkdir test-results
            pipenv run python run.py test

            pytest --junitxml=test-results/junit.xml

            - store_test_results:
                path: test-results

            - store_artifacts:
                path: test-results
workflows:
  version: 2
  tests:
    jobs:
      - tests