version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 5
  two:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 10
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two