version: 2
jobs:
  tests:
    description: "Run tests"
    working_directory: ~/users
    docker:

      - image: circleci/python:3.7.2
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: echo "Run tests"
      - run: pip install --user --upgrade pip
      - run: pip install --user -r requirements.txt
      - run:
          name: run tests
          command: |
            set -oe
            mkdir test-results
            python run.py test
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
workflows:
  version: 2
  tests:
    jobs:
      - tests

