version: 2
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: echo "Run tests"
      - run: pip install -r requirements.txt
      - run: run.py
  two:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 10
workflows:
  version: 2
  one_and_two:
    jobs:
      - run_tests